export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';

export const CART_FETCHED = 'CART_FETCHED';
export const ADDED_TO_CART = 'ADDED_TO_CART';
export const REMOVED_FROM_CART = 'REMOVED_FROM_CART';
export const CART_CLEARED = 'CART_CLEARED';
